config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'listings#index'
  get 'admin', to: 'admins#index'
  get 'listings/admin', to: 'listings#admin_index'
  resources :listings
  resources :profiles, except: [:update]
  patch 'profiles/:id', to: 'profiles#update'
  put 'profiles/:id', to: 'profiles#make_admin'
  resources :chats, except: [:new, :update]
  patch 'chats/:id', to: 'chats#update'
  put 'chats/:id', to: 'chats#reject_offer'
  post 'chats/new/:id', to: 'chats#new', as: 'new_chat'
  resources :purchases, except: [:show, :edit, :update, :destroy]
  get 'purhcases/myorders', to: 'purchases#show'
  post 'chats/:id', to: 'chats#new_message'
  get 'watchlist', to: 'watch_list#index'
  post 'watchlist', to: 'watch_list#create'
  delete 'watchlist', to: 'watch_list#destroy'
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :car
  belongs_to :profile
  has_many :chats, dependent: :destroy
  has_many :listing_modifications, dependent: :destroy
  has_many :modifications, through: :listing_modifications
  has_many :watch_lists, dependent: :destroy
  has_many_attached :car_images
  accepts_nested_attributes_for :modifications, :car
  validates :price, :description, :year, :color, :car_images, presence:true
  validates :description, length: { in: 10..500 }
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_listing, only: [:show, :update, :edit, :destroy]
    before_action :check_auth, only: [:update, :destroy]
    before_action :check_model_auth, only: [:new, :create, :admin_index]
    before_action :filter_results, only: [:index, :admin_index]
    before_action :set_user, only: [:new, :edit]
    before_action :return_modification_types, only: [:show, :new, :edit]
    helper_method :return_mods, :build_search_items

    def index
        profile_setup
    end

    def admin_index
    end

    def show; end

    def new
        authorize Listing
        @listing = Listing.new
        10.times {@listing.modifications.build}
        @listing.build_car
    end

    def create
        authorize Listing
        @listing = Listing.create(listing_params)
        valid_retry('new')
    end

    def edit; end

    def update
        @listing.update(listing_params)
        valid_retry('new')
    end

    def destroy
    authorize @listing
    @listing.destroy
    redirect_to listings_path
    end

  private

#   Ensures a profile must be set up before continuing navigation of website after registration
    def profile_setup
        redirect_to '/profiles/new' if current_user && current_user.profile.nil?
    end

    def listing_params
        params.require(:listing).permit(:car_id, :profile_id, :price, :description, :color, :year, car_images: [],
                                                                                                   car_attributes: [:id, :make, :model], modifications_attributes: [:id, :modification_type, :name])
    end

    def filter_results
        # Query only includes relevant associations for the search
        @q = Listing.includes(:car).joins(:listing_modifications, :modifications).ransack(params[:q])
        @listings = @q.result.distinct
    end

    def valid_retry(action)
        if @listing.valid?
            remove_blank_mods
            redirect_to @listing
        else
            show_error_retry(@listing, action)
        end
    end

    def set_user
        @profile_id = current_user.profile.id
    end

    def check_auth
        authorize @listing
    end

# Used to check auth when a specific instance cannot be loaded (new,create,index)
    def check_model_auth
        authorize Listing
    end

    def find_listing
        # Only including relevant associations with query
        @listing = Listing.includes(:profile, :car_images_attachments, :car).find(params[:id])
    end

# Handles allowing not all of the modification fields to be entered in the new listing page without blank entries remaining in the database
    def remove_blank_mods
        Modification.all.each do |mod|
            if mod.name ==""
                mod.destroy!
            end
        end
    end
    
    # Used to build search items on the index page. DRY's up the search form
    def build_search_items(model, attribute)
        model.select(attribute).distinct.collect {|entity| [entity[attribute], entity[attribute]]}
    end

    # Next two methods are used to dynamically print modifications to the show page for a listing. If new modification types are added, no modification to the show page is required.
    def return_modification_types
        return @mod_types = Modification.distinct.pluck('modification_type')
    end
    
    def return_mods(mod_type)
        if @listing
        return mods = @listing.modifications.where(modifications: { modification_type: mod_type })
        else
          return Modification.where(modifications: { modification_type: mod_type })
        end
    end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_listing.html.erb
<%= form_with model: @listing, data:{turbo:false} do |f| %>
<%= f.hidden_field :profile_id, value: @profile_id %>

<h3 class="mt-2">Car</h3>
<div>
    <%= f.fields_for :car do |f| %>
        <%= f.text_field :make, placeholder: "Make" %>
        <%= f.text_field :model, placeholder: "Model" %>
        <%end%>
  </div>

  <h3 class="mt-2">Details</h3>
<div class="actions mt-2">
<%= f.number_field :year, placeholder: "Year" %>
</div>

<div class="actions mt-2">
<%= f.text_field :color, placeholder: "Color" %>
</div>

<div class="actions mt-2">
<%= f.number_field :price, placeholder: "Price" %>
</div>

<div class="actions mt-2" id='description-div'>
<%= f.text_area :description, placeholder: "Description" %>
</div>

<h3>Modifications</h3>

<% @mod_types.each do |type| %>
    <h5> <%= type %> </h5>
    <% if @listing.year != nil%>
        <%= f.fields_for :modifications, @listing.modifications.where(modification_type:type) do |f| %>
            <%= f.hidden_field :modification_type, value: type %>
            <%= f.text_field :name %>
        <%end%>
    <% else %>
        <%= f.fields_for :modifications do |f| %>
            <%= f.hidden_field :modification_type, value: type %>
            <%= f.text_field :name %>
        <%end%>
    <%end%>
<% end %>

<% if @listing.year == nil %>
<h5 class='mt-3'>Car Images</h5>
    <%= f.file_field :car_images, multiple: true, class:'form-control mt-2', type:'file', id:'formFile' %>
    <% end %>
    <br> <br>
  </div>
  <div>
    <%= f.submit class: 'btn btn-primary'%>
</div>
<% end %>

app/views/listings/_search.html.erb
<%= search_form_for @q do |f| %>
  <%= f.select(:car_make_eq, build_search_items(Car, :make), include_blank: "Make") %>
  <%= f.select(:car_model_eq, build_search_items(Car, :model), include_blank: "Model") %>
<%= f.select(:year_gteq_any, build_search_items(Listing, :year), include_blank: "Year From") %>
<%= f.select(:year_lteq_any, build_search_items(Listing, :year), include_blank: "Year To") %>
<%= f.select(:price_gteq_any, build_search_items(Listing, :price), include_blank: "Price From") %>
<%= f.select(:price_lteq_any, build_search_items(Listing, :price), include_blank: "Price To") %>
  <%= f.select(:color_eq, build_search_items(Listing, :color), include_blank: "Color") %>
  <%= f.select(:modifications_name_eq, build_search_items(Modification, :name), include_blank: "Modification") %>
  <div class="d-flex justify-content-center">
  <%= f.select(:profile_address_state_eq, build_search_items(Address, :state), include_blank: "State") %>
  <%= f.select(:profile_address_city_eq, build_search_items(Address, :city), include_blank: "City") %>
  </div>
  <div class="d-flex justify-content-center mt-2">
  <%= f.submit "Search", class:'btn btn-primary btn-lg btn-block' %>
  </div>
  <% end %>

app/views/listings/admin_index.html.erb
<h1> Listings </h1>

<div class="d-flex justify-content-center">
  <%= render 'search' %>
</div>

    <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Make</th>
      <th scope="col">Model</th>
      <th scope="col">Year</th>
      <th scope="col">Price</th>
      <th scope="col">Created By</th>
      <th scope="col">Created</th>
      <th scope="col">Last Updated</th>
    </tr>
  </thead>
  <tbody>
<% @listings.each do |listing| %>
    <tr>
      <td> <%= listing.id %> </td>
      <td> <%= listing.car.make %> </td>
      <td> <%= listing.car.model %> </td>
      <td> <%= listing.year %> </td>
      <td>$<%= listing.price %> </td>
      <td> <%= listing.profile_id %> </td>
      <td> <%= listing.created_at %> </td>
      <td> <%= listing.updated_at %> </td>
      <td> <%= link_to 'View Record', listing %> </td>
    </tr>
<% end %>
  </tbody>
</table>

app/views/listings/edit.html.erb
<h1>Update your listing</h1>

<%= render 'listing' %>

app/views/listings/index.html.erb
<h1 class="display-1">Listings</h1>

<%= link_to('New Listing', new_listing_path, class: "btn btn-primary btn-lg mb-2") %>

<div class="d-flex justify-content-center">
<%= render 'search' %>
</div>

<% if Listing.all.length != [] %>
  <div class="row">
  <% @listings.each do |listing| %>
    <div class="col-md-6 mt-3">
      <div class="card">
      <div>
      <%= cl_image_tag listing.car_images_attachments.first.key , :background=>"white", :height=>750, :width=>1000, :crop=>"pad", cloud_name: ENV['CLOUDINARY_CLOUD_NAME'], class:"img-fluid center-block d-block mx-auto p-3" %>
      </div>
        <div class="card-body">
          <h3 class="card-title text-center"><%= listing.year%> <%= listing.car.make %> <%= listing.car.model %></h3>
          <p class="card-text text-center"><%= listing.description %></p>
          <ul class="list-group list-group-flush">
      <li class="list-group-item text-center">$<%= listing.price %></li>
      <li class="list-group-item text-center"><%= listing.color.capitalize %></li>
      <li class="list-group-item text-center"><%= listing.profile.address.state %> <%= listing.profile.address.postcode %></li>
      <li class="list-group-item text-center"><%= link_to "View listing", listing, class:"btn btn-outline-info" %></li>
    </ul>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/listings/new.html.erb
<h1>Create your listing</h1>

<%= render 'listing' %>

app/views/listings/show.html.erb
<h1> <%= @listing.year%> <%= @listing.car.make %> <%= @listing.car.model %> </h1>

  <div class="row align-items-center">
<% @listing.car_images_attachments.each do |image| %>
<div class="col-md-4">
    <%= cl_image_tag image.key , crop:'scale', :background=>"white", :width=>600, cloud_name: ENV['CLOUDINARY_CLOUD_NAME'], class:"img-fluid" %>
    </div>
<%end%>
</div>
</div>

<section class="mt-3 d-flex justify-content-center flex-column align-items-center">
<h1>$<%= @listing.price %> </h1>

<h3 class="mt-3">Description</h3>

<%= @listing.description %>

<h3 class="mt-3">Colour</h3>

<%= @listing.color.capitalize %>

<h3 class="mt-3">Modifications</h3>

<% @mod_types.each do |type| %>
    <%if return_mods(type)[0] && return_mods(type)[0].name != ""%>
        <h4 class="mt-4"> <%=type.capitalize%> </h4>
        <% mods = return_mods(type) %> 
        <ul class="list-inline mx-auto justify-content-center w-75">
        <%mods.each do |mod|%>
            <li class="list-group-item text-center "> <%= mod.name.capitalize %>  </li>
        <% end %>
        </ul>
    <% end %>
<% end %>

<% if current_user && current_user.profile.id != @listing.profile.id %>
    <h3 class="mt-3">Contact Seller</h3>
    <%= @listing.profile.first_name %> <%= @listing.profile.last_name %>, <%= @listing.profile.user.email %>
    <span class="d-block"> <%= @listing.profile.address.city %> <%= @listing.profile.address.postcode %> </span>
    </section>
    <div class='mt-3 d-flex justify-content-center flex-column align-items-center'>
    <%= button_to 'Add to your watch list', watchlist_path, method: :post, params: {listing_id: @listing.id, profile_id: current_user.profile.id}, class:'btn btn-info mt-1' %>
    <%= button_to 'Make an enquiry', chats_path(buyer_id: current_user.profile.id, seller_id: @listing.profile_id, listing_id: @listing.id ),method: :post, class:'btn btn-success mt-1' %>
    </div>
<% else %>
    <h3> <%= current_user ? '' : 'Log in to contact seller' %> </h3>
<% end %>

<% if policy(@listing).edit_or_destroy?  %>
    <div class="btn-toolbar mb-1 mt-2" role="toolbar" aria-label="Toolbar with button groups">
    <%= link_to "Edit", edit_listing_path, class:"btn btn-warning" %>
    <%= button_to('Delete', @listing, method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete your listing?" }}, class: "btn btn-danger ms-3") %>
    </div>
<% end %>