config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'listings#index'
  get 'admin', to: 'admins#index'
  get 'listings/admin', to: 'listings#admin_index'
  resources :listings
  resources :profiles, except: [:update]
  patch 'profiles/:id', to: 'profiles#update'
  put 'profiles/:id', to: 'profiles#make_admin'
  resources :chats, except: [:new, :update]
  patch 'chats/:id', to: 'chats#update'
  put 'chats/:id', to: 'chats#reject_offer'
  post 'chats/new/:id', to: 'chats#new', as: 'new_chat'
  resources :purchases, except: [:show, :edit, :update, :destroy]
  get 'purhcases/myorders', to: 'purchases#show'
  post 'chats/:id', to: 'chats#new_message'
  get 'watchlist', to: 'watch_list#index'
  post 'watchlist', to: 'watch_list#create'
  delete 'watchlist', to: 'watch_list#destroy'
end

app/models/address.rb
class Address < ApplicationRecord
    has_many :profiles
    validates :street_number, :street_name, :city, :state, :postcode, :country, presence:true
    validates :street_number, :postcode, numericality: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
    has_many :listings
    has_many :purchases
    validates :make, :model, presence:true
    validates :make, :model, length: { in: 2..30 }
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :buyer, class_name: 'Profile'
  belongs_to :seller, class_name: 'Profile'
  belongs_to :listing
  validates :buyer_id, :seller_id, :listing_id, presence: true

  accepts_nested_attributes_for :messages
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :car
  belongs_to :profile
  has_many :chats, dependent: :destroy
  has_many :listing_modifications, dependent: :destroy
  has_many :modifications, through: :listing_modifications
  has_many :watch_lists, dependent: :destroy
  has_many_attached :car_images
  accepts_nested_attributes_for :modifications, :car
  validates :price, :description, :year, :color, :car_images, presence:true
  validates :description, length: { in: 10..500 }
end

app/models/listing_modification.rb
class ListingModification < ApplicationRecord
  belongs_to :listing
  belongs_to :modification
end

app/models/message.rb
class Message < ApplicationRecord

    belongs_to :chat
    belongs_to :profile
    validates :content, :chat_id, :profile_id, presence:true
    validates :content, length: { maximum: 500 }
    has_one_attached :message_attachment
end

app/models/modification.rb
class Modification < ApplicationRecord
    has_many :listing_modifications
    has_many :listings, through: :listing_modifications, dependent: :destroy
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :address, dependent: :destroy
  has_many :listings
  has_many :watch_lists
  has_many :buyer_purchases, class_name: 'Purchase', foreign_key: 'buyer_id'
  has_many :seller_purchases, class_name: 'Purchase', foreign_key: 'seller_id'
  has_many :buyer_chats, class_name: 'Chat', foreign_key: 'buyer_id'
  has_many :seller_chats, class_name: 'Chat', foreign_key: 'seller_id'
  has_many :messages
  validates_associated :user
  accepts_nested_attributes_for :address
  validates :first_name, :last_name, :date_of_birth, presence: true
  validates :first_name, :last_name, length: { in: 3..50 }
  has_one_attached :avatar
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :car
  belongs_to :buyer, class_name: 'Profile'
  belongs_to :seller, class_name: 'Profile'
  validates :price, presence:true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  has_one :profile, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/watch_list.rb
class WatchList < ApplicationRecord
  belongs_to :listing
  belongs_to :profile
  validates :listing_id, :profile_id, presence:true
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/watch_list_helper.rb
module WatchListHelper
end

app/views/admins/index.html.erb
<%= link_to "Profiles", profiles_path, class:"btn btn-primary btn-lg btn-block mt-5" %>
<%= link_to "Listings", listings_admin_path, class:"btn btn-primary btn-lg btn-block mt-5" %>
<%= link_to "Purchases", purchases_path, class:"btn btn-primary btn-lg btn-block mt-5" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Modified Rides</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    
  </head>
  <body>
<nav class="navbar navbar-expand-md navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Modified Rides</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
          <%if user_signed_in? && current_user.profile %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-md-0 d-flex">
            <li class="nav-item">
              <%= link_to 'Enquiries', chats_path, class: 'nav-link d-inline' %>
              <%= link_to 'Watch list', '/watchlist', class: 'nav-link d-inline' %>
              <%= link_to 'Orders', '/purhcases/myorders', class: 'nav-link d-inline' %>
            </li>
          </ul>
          <% end %>
            <%if user_signed_in? %>
              <%if current_user.profile %>
              <span class='d-flex'>
                Welcome <%= link_to current_user.profile.first_name, "/profiles/#{current_user.profile.id}", class: 'nav-link d-inline pt-0 pb-0' %>
                <% else %>
                Welcome <%= current_user.email %>
                <% end %>
                </span>
              <div class="btn-toolbar mb-1 mt-2" role="toolbar" aria-label="Toolbar with button groups">
                <%= link_to "Admin", admin_path, class:"btn btn-success me-3" if current_user.has_role? :admin %>
                <%= button_to 'Logout', destroy_user_session_path, class: 'btn btn-danger', method: :delete, form: { data: { turbo_confirm: "Are you sure you want to log out?" } } %>
              </span>
              <%else%>
              <span>
                <%= link_to 'Sign-Up', new_user_registration_path, class: 'btn btn-info' %>
                <%= link_to 'Sign-in', new_user_session_path, class: 'btn btn-info' %>
              </span>
            <%end%>
        </div>
      </div>
    </nav>
<main class='p-4 d-flex justify-content-center flex-column align-items-center'>
  <% if notice %>
  <p class="alert alert-success"><%= flash[:notice].html_safe %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= flash[:alert].html_safe %></p>
<% end %>
    <%= yield %>
    </main>
  </body>
</html>